#ifndef STATIC_COMPONENTS_HPP
#define STATIC_COMPONENTS_HPP

namespace talorion {
  typedef enum static_component_id {
    NAME_COMPONENT,
    HOST_NAME_COMPONENT,
    PORT_COMPONENT,
    BOX_ID_COMPONENT,
    TIMEOUT_COMPONENT,
    CONNECTION_STATE_COMPONENT,
    SERIAL_VERSION_UID_COMPONENT,
    COMMAND_STATE_COMPONENT
    //UNITS_COMPONENT,
    //SET_MIN_COMPONENT,
    //SET_MAX_COMPONENT,
    //ACT_MIN_COMPONENT,
    //ACT_MAX_COMPONENT,
    //ANALOG_SET_VALUE_COMPONENT,
    //ANALOG_ACT_VALUE_COMPONENT,
    //ID_COMPONENT,
    //DIGITAL_SET_VALUE_COMPONENT,
    //DIGITAL_ACT_VALUE_COMPONENT,
    //SYSTEM_CONFIGURAION_WIDGET_COMPONENT,
    //IS_SYSTEM_COMPONENT,
    //CONNECTION_STATE_COMPONENT,
    //TCP_BOX_BACKEND_COMPONENT,
    //SYSTEM_VERSION_UID_COMPONENT,
    //QT_SCRIPT_ENGINE_COMPONENT,
    //SCRIPT_FILE_COMPONENT,
    //DATA_AQUISITION_DLL_COMPONENT,
    //TIMEOUT_COMPONENT,
    //SCRIPTABLE_OBJECT_COMPONENT,
    //FILEVERSION_COMPONENT,
    //PRODUCTVERSION_COMPONENT,
    //COMPANYNAME_COMPONENT,
    //UPDATERATE_COMPONENT,
    //USER_DATA_COMPONENT,
    //USER_DATA_PATH_COMPONENT,
  } static_component_id;
}

#endif // STATIC_COMPONENTS_HPP

