#ifndef TCPBOXSYSTEM_GLOBAL_HPP
#define TCPBOXSYSTEM_GLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(TCPBOX_SYSTEM_LIBRARY)
#  define TCPBOXSYSTEMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TCPBOXSYSTEMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TCPBOXSYSTEM_GLOBAL_HPP
