#ifndef STATICCOMPONENTID_HPP
#define STATICCOMPONENTID_HPP

namespace talorion {

//StaticComponentId;

typedef enum static_component_id {
    IP_ADDRESS_COMPONENT,
    PORT_COMPONENT,
    NAME_COMPONENT,
    UNITS_COMPONENT,
    SET_MIN_COMPONENT,
    SET_MAX_COMPONENT,
    ACT_MIN_COMPONENT,
    ACT_MAX_COMPONENT,
    ANALOG_SET_VALUE_COMPONENT,
    ANALOG_ACT_VALUE_COMPONENT,
    ID_COMPONENT,
    BOX_ID_COMPONENT,
    BOX_COMPONENT,
    DIGITAL_SET_VALUE_COMPONENT,
    DIGITAL_ACT_VALUE_COMPONENT,
    SYSTEM_CONFIGURAION_WIDGET_COMPONENT,
    IS_SYSTEM_COMPONENT,
    CONNECTION_STATE_COMPONENT,
    SERIAL_VERSION_UID_COMPONENT,
    TCP_BOX_BACKEND_COMPONENT,
    SYSTEM_VERSION_UID_COMPONENT,
    QT_SCRIPT_ENGINE_COMPONENT,
    SCRIPT_FILE_COMPONENT,
    DATA_AQUISITION_DLL_COMPONENT,
    DLL_PATH_COMPONENT,
    DAQ_DATA_ID_COMPONENT,
    STATE_COMPONENT,
    TIMEOUT_COMPONENT,
    SCRIPTABLE_OBJECT_COMPONENT,
    FILEVERSION_COMPONENT,
    PRODUCTVERSION_COMPONENT,
    COMPANYNAME_COMPONENT,
    UPDATERATE_COMPONENT,
    USER_DATA_COMPONENT,
    USER_DATA_PATH_COMPONENT,
    SPECTRUM_COMPONENT,
    CYCLE_COMPONENT,
    PARENT_COMPONENT,
    CHILDREN_COMPONENT,
    SYSTEM_COMPONENT,
    SYSTEM_VIEW_WIDGET_COMPONENT,
    SYSTEM_TOOLBARS_COMPONENT,
    SYSTEM_ACTIONS_COMPONENT,
    IGNORE_WHILE_SAVEING_COMPONENT,
    PARAMETER_TYPES_COMPONENT,
    PARAMETER_NAMES_COMPONENT,
    METHOD_ID_COMPONENT,
    AUTO_RECONNECT_COMPONENT,
    METADATA_COMPONENT,
    BOX_TRANSPORT_COMPONENT
} static_component_id;
}

Q_DECLARE_METATYPE(talorion::static_component_id)

#endif // STATICCOMPONENTID_HPP
