#ifndef TCP_BOX_SYSTEM_GLOBAL_HPP
#define TCP_BOX_SYSTEM_GLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(TCP_BOX_SYSTEM_LIBRARY)
#  define TCP_BOX_SYSTEMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TCP_BOX_SYSTEMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TCP_BOX_SYSTEM_GLOBAL_HPP
