#ifndef QECMDCLIENT_GLOBAL_HPP
#define QECMDCLIENT_GLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(QECMDCLIENT_LIBRARY)
#  define QECMDCLIENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QECMDCLIENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QECMDCLIENT_GLOBAL_HPP
