#ifndef QTOFDAQDLL_GLOBAL_HPP
#define QTOFDAQDLL_GLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(QTOFDAQDLL_LIBRARY)
#  define QTOFDAQDLLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTOFDAQDLLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTOFDAQDLL_GLOBAL_HPP
